# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aEQOpL8A3hWBpqZr813RYrvJC_eVQHs
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("boulahchichenadir/algerian-used-cars")

print("Path to dataset files:", path)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from pathlib import Path

# Set seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

print(tf.config.list_physical_devices('GPU'))


# Configurations
IMG_HEIGHT = 224
IMG_WIDTH = 224
BATCH_SIZE = 32
INITIAL_EPOCHS = 10
FINE_TUNE_EPOCHS = 10
TOTAL_EPOCHS = INITIAL_EPOCHS + FINE_TUNE_EPOCHS

# Update this to your dataset location
DATA_DIR = "./dataset/DATA/"


"""# Prepare dataframes & generators"""

def prepare_generators(data_dir):
    df = []
    for class_folder in sorted(Path(data_dir).iterdir()):
        if class_folder.is_dir():
            for img in class_folder.glob('*'):
                if img.suffix.lower() in ['.jpg', '.jpeg', '.png']:
                    df.append({'filename': str(img), 'class': class_folder.name})
    df = pd.DataFrame(df)
    print("Total images:", len(df), "Classes:", df['class'].nunique())

    train_df, temp = train_test_split(df, test_size=0.3, stratify=df['class'], random_state=42)
    val_df, test_df = train_test_split(temp, test_size=0.5, stratify=temp['class'], random_state=42)
    print("Split sizes:", train_df.shape[0], val_df.shape[0], test_df.shape[0])

    train_aug = ImageDataGenerator(
        rescale=1./255, rotation_range=30, width_shift_range=0.2, height_shift_range=0.2,
        shear_range=0.2, zoom_range=0.2, horizontal_flip=True, brightness_range=[0.7,1.3],
        fill_mode='nearest'
    )
    basic = ImageDataGenerator(rescale=1./255)

    train_gen = train_aug.flow_from_dataframe(train_df, x_col='filename', y_col='class',
                                               target_size=(IMG_HEIGHT, IMG_WIDTH),
                                               batch_size=BATCH_SIZE, class_mode='categorical', shuffle=True)
    val_gen = basic.flow_from_dataframe(val_df, x_col='filename', y_col='class',
                                        target_size=(IMG_HEIGHT, IMG_WIDTH),
                                        batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False)
    test_gen = basic.flow_from_dataframe(test_df, x_col='filename', y_col='class',
                                         target_size=(IMG_HEIGHT, IMG_WIDTH),
                                         batch_size=BATCH_SIZE, class_mode='categorical', shuffle=False)
    return train_gen, val_gen, test_gen

train_gen, val_gen, test_gen = prepare_generators(DATA_DIR)
NUM_CLASSES = len(train_gen.class_indices)
print("Number of classes:", NUM_CLASSES)

"""#ompile and train top layers"""

def build_tl_model(input_shape, num_classes):
    base = keras.applications.MobileNetV2(input_shape=input_shape, include_top=False, weights='imagenet')
    base.trainable = False
    inputs = keras.Input(shape=input_shape)
    x = keras.applications.mobilenet_v2.preprocess_input(inputs)
    x = base(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.4)(x)
    x = layers.Dense(256, activation='relu')(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)
    return keras.Model(inputs, outputs), base

model, base_model = build_tl_model((IMG_HEIGHT, IMG_WIDTH, 3), NUM_CLASSES)
model.summary()

"""#Compile and train top layers"""

def compile_and_train(m, train_gen, val_gen, lr, epochs, model_name):
    m.compile(
        optimizer=keras.optimizers.Adam(lr),
        loss='categorical_crossentropy',
        metrics=['accuracy', keras.metrics.TopKCategoricalAccuracy(k=5, name='top-5')]
    )
    callbacks = [
        EarlyStopping('val_loss', patience=5, restore_best_weights=True),
        ReduceLROnPlateau('val_loss', patience=3, factor=0.5),
        ModelCheckpoint(f"{model_name}_best.h5", monitor='val_accuracy', save_best_only=True)
    ]
    return m.fit(train_gen, validation_data=val_gen, epochs=epochs, callbacks=callbacks, verbose=1)

print("\nPhase 1: Training top layers")
history1 = compile_and_train(model, train_gen, val_gen, lr=1e-3, epochs=INITIAL_EPOCHS, model_name="phase1")

"""#Fine-tune last layers of the base"""

print("\nPhase 2: Fine-tuning")
base_model.trainable = True
for layer in base_model.layers[:-40]:
    layer.trainable = False

history2 = compile_and_train(model, train_gen, val_gen, lr=1e-5, epochs=FINE_TUNE_EPOCHS, model_name="phase2")

"""Combine history and plot"""

import matplotlib.pyplot as plt
acc = history1.history['accuracy'] + history2.history['accuracy']
val_acc = history1.history['val_accuracy'] + history2.history['val_accuracy']
loss = history1.history['loss'] + history2.history['loss']
val_loss = history1.history['val_loss'] + history2.history['val_loss']

plt.figure(figsize=(12, 5))
plt.subplot(1,2,1)
plt.plot(acc, label='Train Acc')
plt.plot(val_acc, label='Val Acc')
plt.title('Accuracy'); plt.xlabel('Epoch'); plt.legend()
plt.subplot(1,2,2)
plt.plot(loss, label='Train Loss')
plt.plot(val_loss, label='Val Loss')
plt.title('Loss'); plt.xlabel('Epoch'); plt.legend()
plt.show()

"""#Evaluate on test set"""

print("\nEvaluating on test set:")
results = model.evaluate(test_gen, verbose=1)
print(f"Test Loss: {results[0]:.4f}, Accuracy: {results[1]:.4f}, Top-5 Accuracy: {results[2]:.4f}")

"""#Save final model"""

model.save("algerian_cars_mobilenet_finetuned.h5")
print("Model saved.")